### PR TITLE
functions.inc.php: escape minus in regex

### PR DESCRIPTION
**Pull request by julianbrost**
This makes CGP work on PHP 7.3 as it otherwise only shows an "Unknown
host" error message and logs the following PHP warning:

PHP Warning:  preg_match(): Compilation failed: invalid range in
character class at offset 4 in .../inc/functions.inc.php on line 37

Apart from that, CGP seems to work fine with PHP 7.3.

### CODE REVIEW

**Comment by pommi** [comment]
Thanks 👍
